<a href="https://colab.research.google.com/github/kkeshavsharma/NLP_Practice/blob/main/NLP_prac_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###**IMPORTING**

In [40]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.naive_bayes import MultinomialNB

In [52]:
df = pd.read_parquet("comments_data_13.parquet")
df

,video_id,channel_id,comment_id,author_display_name,author_channel_id,text_display,like_count,published_at,updated_at
0,VTWU6-ht-hw,UCxykVmXr1GwZZZxKG8ZRaUg,UgwLRsFzC2xH8KyGqXh4AaABAg,@OfficersAdda247,UCxykVmXr1GwZZZxKG8ZRaUg,✅ Officer&#39;s batch (Bilingual)📌 Join Now <...,0,2025-08-03T04:29:18Z,2025-08-03T04:29:18Z
1,Nkm3rxndZzk,UCxykVmXr1GwZZZxKG8ZRaUg,Ugz7xb70XtaW9abaedF4AaABAg,@OfficersAdda247,UCxykVmXr1GwZZZxKG8ZRaUg,✅ Officer&#39;s batch (Bilingual)📌 Join Now <...,0,2025-08-03T04:30:23Z,2025-08-03T04:30:23Z
2,HbZQy09kkvM,UCxykVmXr1GwZZZxKG8ZRaUg,UgwKwhTXsyveAKxvFu14AaABAg,@OfficersAdda247,UCxykVmXr1GwZZZxKG8ZRaUg,✅ Officer&#39;s batch (Bilingual)📌 Join Now <...,0,2025-08-03T04:43:12Z,2025-08-03T04:43:12Z
3,XdTBRbUtIyg,UCxykVmXr1GwZZZxKG8ZRaUg,UgxkPpDtztRwRWPrm0l4AaABAg,@OfficersAdda247,UCxykVmXr1GwZZZxKG8ZRaUg,🔔 JAIIB Registration is LIVE Now!<br>🚨 Having ...,0,2025-08-03T03:50:33Z,2025-08-03T03:50:33Z
4,yeGNz3XTVGg,UCxykVmXr1GwZZZxKG8ZRaUg,UgyoWsvWzdcK5bqbcjJ4AaABAg,@OfficersAdda247,UCxykVmXr1GwZZZxKG8ZRaUg,🔔 JAIIB Registration is LIVE Now!<br>🚨 Having ...,0,2025-08-03T03:50:20Z,2025-08-03T03:50:20Z
...,...,...,...,...,...,...,...,...,...
28086,2lEbFBYybDo,UCxykVmXr1GwZZZxKG8ZRaUg,Ugw4qTBvOHb3VUTvwbl4AaABAg,@OfficersAdda247,UCxykVmXr1GwZZZxKG8ZRaUg,AIIB &amp; CAIIB 2023 ALL LATEST STUDY MATERIA...,0,2023-10-12T17:16:14Z,2023-10-12T17:16:14Z
28087,2lEbFBYybDo,UCxykVmXr1GwZZZxKG8ZRaUg,UgziYRSXkEdp2dmFmTJ4AaABAg,@anmoljadhav123,UCvGeqmoDRDvRl9EawCeatFA,"Thanks for the session mam , my exam went well...",0,2023-10-15T11:24:35Z,2023-10-15T11:24:35Z
28088,2lEbFBYybDo,UCxykVmXr1GwZZZxKG8ZRaUg,Ugzk_slK1Ls_m0Pjhd94AaABAg,@ramrawat6336,UCjlT0Il2pIgXM4yxbCpPExQ,Grt efforts 🙏,0,2023-10-14T17:00:34Z,2023-10-14T17:00:34Z
28089,2lEbFBYybDo,UCxykVmXr1GwZZZxKG8ZRaUg,UgzIr1bUnzPC-0vOUX94AaABAg,@divismiley8607,UC5LR40fB5Y3j2g4tAlECFjg,Pdf,0,2023-10-14T16:22:11Z,2023-10-14T16:22:11Z
28090,vhyFTid0vfE,UCxykVmXr1GwZZZxKG8ZRaUg,Ugw6sNU0dRgs8OM9-bF4AaABAg,@OfficersAdda247,UCxykVmXr1GwZZZxKG8ZRaUg,JAIIB &amp; CAIIB 2023 ALL LATEST STUDY MATERI...,0,2023-10-11T05:13:45Z,2023-10-11T05:13:45Z

In [53]:
df = df[df["channel_id"] != df["author_channel_id"]]
df = df[df["like_count"] == 1]
df

,video_id,channel_id,comment_id,author_display_name,author_channel_id,text_display,like_count,published_at,updated_at
25,urO82djZqhE,UCxykVmXr1GwZZZxKG8ZRaUg,UgxAwhI9uN7Pdy7nfxt4AaABAg,@arj374,UCU3ry1U_ipyWQdraKNOmDjQ,Is Declaration mandatory for old Members?,1,2025-08-01T15:17:37Z,2025-08-01T15:17:37Z
112,4codsIc9p34,UCxykVmXr1GwZZZxKG8ZRaUg,Ugz2mWPJpdqTJkzItu94AaABAg,@dailytechdose007,UCBxuBA-DU4uFxYQJvjxh4lA,I&#39;ve completed IT security in 2020<br>Rema...,1,2025-08-12T09:06:26Z,2025-08-12T09:06:26Z
169,_xir_g4a-jc,UCxykVmXr1GwZZZxKG8ZRaUg,UgxM3bJx5onoQv7Kd4x4AaABAg,@VikasSinghbanker,UChkaOR_vzyBFvjvRgciZslA,"Sir While taking membership of IIBF, name of U...",1,2025-07-27T07:36:12Z,2025-07-27T07:36:12Z
182,jUg9cmsVvmQ,UCxykVmXr1GwZZZxKG8ZRaUg,UgzuOo2pj1uHQ4lOncN4AaABAg,@LifeZindagiMotivation,UCiKnpwmgMk4AgnCXWzvxLAA,Jaiib may certificate kb ayega??,1,2025-07-26T10:59:15Z,2025-07-26T10:59:15Z
242,Hs1H0AK5kc8,UCxykVmXr1GwZZZxKG8ZRaUg,UgzjKudxj3x0rlX2hll4AaABAg,@AruChouhan-h9x,UCdx6wqVn4oaaF19D5BgQuFQ,Thanks mam aapke karan hi ye possible ho paya ...,1,2025-07-24T17:27:12Z,2025-07-24T17:27:12Z
...,...,...,...,...,...,...,...,...,...
28071,W2y9KGA0V-s,UCxykVmXr1GwZZZxKG8ZRaUg,Ugx83N2dU4VHyB2dpI94AaABAg,@1dayexams803,UCg2H20CNiV_J0AgaltI0wCw,Q32 <br>More than one will be the answer,1,2023-10-11T14:02:08Z,2023-10-11T14:02:08Z
28075,l7rdyynxlqU,UCxykVmXr1GwZZZxKG8ZRaUg,Ugwz5MTc7fDHLCo0BlV4AaABAg,@VileshKedare-x2g,UCAhZu671v300GjGfHW6U9mQ,Thank you so much for your valuable support,1,2024-12-29T08:50:38Z,2024-12-29T08:50:38Z
28079,l7rdyynxlqU,UCxykVmXr1GwZZZxKG8ZRaUg,Ugx23ZGiE2oa1m1XC394AaABAg,@vikrantdubey7818,UCOPHfQ5ruOMmOPXAVpFZpjg,Aur your energy is..... unbelievable to believ...,1,2023-10-13T16:52:54Z,2023-10-13T16:52:54Z
28081,l7rdyynxlqU,UCxykVmXr1GwZZZxKG8ZRaUg,UgzIV1k7ijOmGddvxV54AaABAg,@shilpaarora3763,UCx-G4Br-gzmrywvFqVcqSHQ,Thank you for such a great session,1,2023-10-13T02:56:00Z,2023-10-13T02:56:00Z
28084,l7rdyynxlqU,UCxykVmXr1GwZZZxKG8ZRaUg,UgwL2aIcHUoJeP2hMsB4AaABAg,@shilpisankhawar379,UCrvvd8S69qMmET-4GOa4OJg,🙏,1,2023-10-12T11:21:40Z,2023-10-12T11:21:40Z

In [56]:
len(df)

1001

In [54]:
df = df.drop_duplicates(subset = ["text_display"])
df

,video_id,channel_id,comment_id,author_display_name,author_channel_id,text_display,like_count,published_at,updated_at
25,urO82djZqhE,UCxykVmXr1GwZZZxKG8ZRaUg,UgxAwhI9uN7Pdy7nfxt4AaABAg,@arj374,UCU3ry1U_ipyWQdraKNOmDjQ,Is Declaration mandatory for old Members?,1,2025-08-01T15:17:37Z,2025-08-01T15:17:37Z
112,4codsIc9p34,UCxykVmXr1GwZZZxKG8ZRaUg,Ugz2mWPJpdqTJkzItu94AaABAg,@dailytechdose007,UCBxuBA-DU4uFxYQJvjxh4lA,I&#39;ve completed IT security in 2020<br>Rema...,1,2025-08-12T09:06:26Z,2025-08-12T09:06:26Z
169,_xir_g4a-jc,UCxykVmXr1GwZZZxKG8ZRaUg,UgxM3bJx5onoQv7Kd4x4AaABAg,@VikasSinghbanker,UChkaOR_vzyBFvjvRgciZslA,"Sir While taking membership of IIBF, name of U...",1,2025-07-27T07:36:12Z,2025-07-27T07:36:12Z
182,jUg9cmsVvmQ,UCxykVmXr1GwZZZxKG8ZRaUg,UgzuOo2pj1uHQ4lOncN4AaABAg,@LifeZindagiMotivation,UCiKnpwmgMk4AgnCXWzvxLAA,Jaiib may certificate kb ayega??,1,2025-07-26T10:59:15Z,2025-07-26T10:59:15Z
242,Hs1H0AK5kc8,UCxykVmXr1GwZZZxKG8ZRaUg,UgzjKudxj3x0rlX2hll4AaABAg,@AruChouhan-h9x,UCdx6wqVn4oaaF19D5BgQuFQ,Thanks mam aapke karan hi ye possible ho paya ...,1,2025-07-24T17:27:12Z,2025-07-24T17:27:12Z
...,...,...,...,...,...,...,...,...,...
28071,W2y9KGA0V-s,UCxykVmXr1GwZZZxKG8ZRaUg,Ugx83N2dU4VHyB2dpI94AaABAg,@1dayexams803,UCg2H20CNiV_J0AgaltI0wCw,Q32 <br>More than one will be the answer,1,2023-10-11T14:02:08Z,2023-10-11T14:02:08Z
28075,l7rdyynxlqU,UCxykVmXr1GwZZZxKG8ZRaUg,Ugwz5MTc7fDHLCo0BlV4AaABAg,@VileshKedare-x2g,UCAhZu671v300GjGfHW6U9mQ,Thank you so much for your valuable support,1,2024-12-29T08:50:38Z,2024-12-29T08:50:38Z
28079,l7rdyynxlqU,UCxykVmXr1GwZZZxKG8ZRaUg,Ugx23ZGiE2oa1m1XC394AaABAg,@vikrantdubey7818,UCOPHfQ5ruOMmOPXAVpFZpjg,Aur your energy is..... unbelievable to believ...,1,2023-10-13T16:52:54Z,2023-10-13T16:52:54Z
28081,l7rdyynxlqU,UCxykVmXr1GwZZZxKG8ZRaUg,UgzIV1k7ijOmGddvxV54AaABAg,@shilpaarora3763,UCx-G4Br-gzmrywvFqVcqSHQ,Thank you for such a great session,1,2023-10-13T02:56:00Z,2023-10-13T02:56:00Z
28084,l7rdyynxlqU,UCxykVmXr1GwZZZxKG8ZRaUg,UgwL2aIcHUoJeP2hMsB4AaABAg,@shilpisankhawar379,UCrvvd8S69qMmET-4GOa4OJg,🙏,1,2023-10-12T11:21:40Z,2023-10-12T11:21:40Z

In [55]:
df = df.groupby('video_id')['text_display'].apply(lambda x: ' '.join(x)).reset_index()

In [46]:
import re
def clean_str(series: pd.Series) -> pd.Series:
  series = series.fillna("").astype(str)

  series = series.str.replace(r"https?://\S+|www\.\S+", "", regex = True)
  series = series.str.replace(r"<[^<>]*>", "", regex = True)

  series = series.str.replace(r"['’][sS]\b","",regex = True)

  series = series.str.replace(r"\b\d{1,2}:\d{2}(:\d{2})?\b", "", regex = True)

  series = series.str.replace(r"(.)\1{2,}", r"\1\1", regex = True)

  series = series.str.replace(r"\s+"," ", regex = True).str.strip()
  return series

clean_df = clean_str(df["text_display"])

In [47]:
clean_df

0     Bina negative marking ke 45-50 nhi aa rhe Ye o...
1     To hamaara india aisa kyu he kaha aise job ke ...
2     Always been fan of your teaching ma&#39;am sin...
3                          Modiji should also retire 😅😅
4     It&#39;s Better For IIBF to Make Available Res...
                            ...
90                              IE and IES was not easy
91    Sir please provide chalisa class 1 day before ...
92    Your team is continuously calling day and nigh...
93    Kahan likha hai 6 months? Don&#39;t spread rum...
94    Mam ye soch ke padaiye ki hum student sab non ...
Name: text_display, Length: 95, dtype: object

In [48]:
vectorizer = CountVectorizer()
vec = vectorizer.fit_transform(df)
vec

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (2, 2)>

In [51]:
print(vec)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (2, 2)>
  Coords	Values
  (0, 1)	1
  (1, 0)	1