<a href="https://colab.research.google.com/github/kkeshavsharma/NLP_Practice/blob/main/NLP_prac_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [102]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.naive_bayes import MultinomialNB
import html
import re

In [103]:
df = pd.read_parquet("comments_data_13.parquet")
df

,video_id,channel_id,comment_id,author_display_name,author_channel_id,text_display,like_count,published_at,updated_at
0,VTWU6-ht-hw,UCxykVmXr1GwZZZxKG8ZRaUg,UgwLRsFzC2xH8KyGqXh4AaABAg,@OfficersAdda247,UCxykVmXr1GwZZZxKG8ZRaUg,✅ Officer&#39;s batch (Bilingual)📌 Join Now <...,0,2025-08-03T04:29:18Z,2025-08-03T04:29:18Z
1,Nkm3rxndZzk,UCxykVmXr1GwZZZxKG8ZRaUg,Ugz7xb70XtaW9abaedF4AaABAg,@OfficersAdda247,UCxykVmXr1GwZZZxKG8ZRaUg,✅ Officer&#39;s batch (Bilingual)📌 Join Now <...,0,2025-08-03T04:30:23Z,2025-08-03T04:30:23Z
2,HbZQy09kkvM,UCxykVmXr1GwZZZxKG8ZRaUg,UgwKwhTXsyveAKxvFu14AaABAg,@OfficersAdda247,UCxykVmXr1GwZZZxKG8ZRaUg,✅ Officer&#39;s batch (Bilingual)📌 Join Now <...,0,2025-08-03T04:43:12Z,2025-08-03T04:43:12Z
3,XdTBRbUtIyg,UCxykVmXr1GwZZZxKG8ZRaUg,UgxkPpDtztRwRWPrm0l4AaABAg,@OfficersAdda247,UCxykVmXr1GwZZZxKG8ZRaUg,🔔 JAIIB Registration is LIVE Now!<br>🚨 Having ...,0,2025-08-03T03:50:33Z,2025-08-03T03:50:33Z
4,yeGNz3XTVGg,UCxykVmXr1GwZZZxKG8ZRaUg,UgyoWsvWzdcK5bqbcjJ4AaABAg,@OfficersAdda247,UCxykVmXr1GwZZZxKG8ZRaUg,🔔 JAIIB Registration is LIVE Now!<br>🚨 Having ...,0,2025-08-03T03:50:20Z,2025-08-03T03:50:20Z
...,...,...,...,...,...,...,...,...,...
28086,2lEbFBYybDo,UCxykVmXr1GwZZZxKG8ZRaUg,Ugw4qTBvOHb3VUTvwbl4AaABAg,@OfficersAdda247,UCxykVmXr1GwZZZxKG8ZRaUg,AIIB &amp; CAIIB 2023 ALL LATEST STUDY MATERIA...,0,2023-10-12T17:16:14Z,2023-10-12T17:16:14Z
28087,2lEbFBYybDo,UCxykVmXr1GwZZZxKG8ZRaUg,UgziYRSXkEdp2dmFmTJ4AaABAg,@anmoljadhav123,UCvGeqmoDRDvRl9EawCeatFA,"Thanks for the session mam , my exam went well...",0,2023-10-15T11:24:35Z,2023-10-15T11:24:35Z
28088,2lEbFBYybDo,UCxykVmXr1GwZZZxKG8ZRaUg,Ugzk_slK1Ls_m0Pjhd94AaABAg,@ramrawat6336,UCjlT0Il2pIgXM4yxbCpPExQ,Grt efforts 🙏,0,2023-10-14T17:00:34Z,2023-10-14T17:00:34Z
28089,2lEbFBYybDo,UCxykVmXr1GwZZZxKG8ZRaUg,UgzIr1bUnzPC-0vOUX94AaABAg,@divismiley8607,UC5LR40fB5Y3j2g4tAlECFjg,Pdf,0,2023-10-14T16:22:11Z,2023-10-14T16:22:11Z
28090,vhyFTid0vfE,UCxykVmXr1GwZZZxKG8ZRaUg,Ugw6sNU0dRgs8OM9-bF4AaABAg,@OfficersAdda247,UCxykVmXr1GwZZZxKG8ZRaUg,JAIIB &amp; CAIIB 2023 ALL LATEST STUDY MATERI...,0,2023-10-11T05:13:45Z,2023-10-11T05:13:45Z

In [104]:
df = df[df["channel_id"] != df["author_channel_id"]]
# df = df[df["like_count"] == 1]
df

,video_id,channel_id,comment_id,author_display_name,author_channel_id,text_display,like_count,published_at,updated_at
7,0voLlAL61uU,UCxykVmXr1GwZZZxKG8ZRaUg,UgxlUCWa6hZjGYlYToF4AaABAg,@akashukey1776,UC3qF3oGXTLXVjwSSih20-sA,sir i work in raigad but i want nagpur centre ...,0,2026-08-20T15:46:13Z,2026-08-20T15:46:13Z
8,0voLlAL61uU,UCxykVmXr1GwZZZxKG8ZRaUg,UgxmGGHMdRlPS0KKBGh4AaABAg,@Gamingbiason1992,UCU8qHDVkH5cReCoLMMEZCVA,Sir agar transfer ho Gaya ek state Se dusre st...,0,2026-05-05T03:11:32Z,2026-05-05T03:11:32Z
9,0voLlAL61uU,UCxykVmXr1GwZZZxKG8ZRaUg,UgxnMEb6wDYsA4ZFw8J4AaABAg,@twinkleverma4392,UCbper4TF3tilIR-qdy0pa7w,Sir if my place of work is mumbai can I select...,0,2025-08-21T17:40:44Z,2025-08-21T17:40:44Z
20,AHcawlXBuag,UCxykVmXr1GwZZZxKG8ZRaUg,UgwNqOtjfEJzUjkTjtR4AaABAg,@RPG1990,UCQ9fEiwxwapY1U5vCOQxGvQ,Pdf milega is lecture ka ?,0,2025-08-17T05:43:51Z,2025-08-17T05:43:51Z
24,urO82djZqhE,UCxykVmXr1GwZZZxKG8ZRaUg,UgyFzrpBgjkJl2ol-vJ4AaABAg,@babulgupta4833,UC_LR4Ja6j9M-4FMaF4OM9mw,Mere pass id card nhi h ... bhar paunga ki nhi...,0,2025-08-27T19:29:57Z,2025-08-27T19:29:57Z
...,...,...,...,...,...,...,...,...,...
28084,l7rdyynxlqU,UCxykVmXr1GwZZZxKG8ZRaUg,UgwL2aIcHUoJeP2hMsB4AaABAg,@shilpisankhawar379,UCrvvd8S69qMmET-4GOa4OJg,🙏,1,2023-10-12T11:21:40Z,2023-10-12T11:21:40Z
28085,l7rdyynxlqU,UCxykVmXr1GwZZZxKG8ZRaUg,UgyPKxwRcx6e7QjAcBl4AaABAg,@asdfghj1227,UCaR6Ch_HMdQUbFCXLIh-lYg,"Sir most answers are c, why",2,2023-10-12T06:47:20Z,2023-10-12T06:47:20Z
28087,2lEbFBYybDo,UCxykVmXr1GwZZZxKG8ZRaUg,UgziYRSXkEdp2dmFmTJ4AaABAg,@anmoljadhav123,UCvGeqmoDRDvRl9EawCeatFA,"Thanks for the session mam , my exam went well...",0,2023-10-15T11:24:35Z,2023-10-15T11:24:35Z
28088,2lEbFBYybDo,UCxykVmXr1GwZZZxKG8ZRaUg,Ugzk_slK1Ls_m0Pjhd94AaABAg,@ramrawat6336,UCjlT0Il2pIgXM4yxbCpPExQ,Grt efforts 🙏,0,2023-10-14T17:00:34Z,2023-10-14T17:00:34Z
28089,2lEbFBYybDo,UCxykVmXr1GwZZZxKG8ZRaUg,UgzIr1bUnzPC-0vOUX94AaABAg,@divismiley8607,UC5LR40fB5Y3j2g4tAlECFjg,Pdf,0,2023-10-14T16:22:11Z,2023-10-14T16:22:11Z

In [105]:
# 1. First, apply your hard constraints (drop HTML, author comments, and short spam)
df = df[df['text_display'].str.split().str.len() >= 10]

# 2. Create a 'Quality Score': Word Count gives text depth, plus a small boost for likes
# This ensures long, thoughtful questions with 0 likes beat out a 2-word comment with 50 likes
df['quality_score'] = df['text_display'].str.split().str.len() + (df['like_count'] * 2)

# 3. Sort by video and quality, then slice the top 20 comments for every single video
df_top_comments = (
    df.sort_values(by=['video_id', 'quality_score'], ascending=[False, True])
    .groupby('video_id')
    .head(20)  # Keep up to the 20 best comments per video
)

/tmp/ipykernel_659/2805650470.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['quality_score'] = df['text_display'].str.split().str.len() + (df['like_count'] * 2)

In [106]:
df

,video_id,channel_id,comment_id,author_display_name,author_channel_id,text_display,like_count,published_at,updated_at,quality_score
7,0voLlAL61uU,UCxykVmXr1GwZZZxKG8ZRaUg,UgxlUCWa6hZjGYlYToF4AaABAg,@akashukey1776,UC3qF3oGXTLXVjwSSih20-sA,sir i work in raigad but i want nagpur centre ...,0,2026-08-20T15:46:13Z,2026-08-20T15:46:13Z,16
8,0voLlAL61uU,UCxykVmXr1GwZZZxKG8ZRaUg,UgxmGGHMdRlPS0KKBGh4AaABAg,@Gamingbiason1992,UCU8qHDVkH5cReCoLMMEZCVA,Sir agar transfer ho Gaya ek state Se dusre st...,0,2026-05-05T03:11:32Z,2026-05-05T03:11:32Z,17
9,0voLlAL61uU,UCxykVmXr1GwZZZxKG8ZRaUg,UgxnMEb6wDYsA4ZFw8J4AaABAg,@twinkleverma4392,UCbper4TF3tilIR-qdy0pa7w,Sir if my place of work is mumbai can I select...,0,2025-08-21T17:40:44Z,2025-08-21T17:40:44Z,17
24,urO82djZqhE,UCxykVmXr1GwZZZxKG8ZRaUg,UgyFzrpBgjkJl2ol-vJ4AaABAg,@babulgupta4833,UC_LR4Ja6j9M-4FMaF4OM9mw,Mere pass id card nhi h ... bhar paunga ki nhi...,0,2025-08-27T19:29:57Z,2025-08-27T19:29:57Z,12
33,masJDyVfIzo,UCxykVmXr1GwZZZxKG8ZRaUg,Ugzi2B5hQirDpctlaIN4AaABAg,@kavitavashisth787,UCHN_pEggqtarwvPqQ9qTN6w,Mam pehle membership fees 1700 something lgii ...,0,2025-08-25T17:23:11Z,2025-08-25T17:23:11Z,22
...,...,...,...,...,...,...,...,...,...,...
28069,W2y9KGA0V-s,UCxykVmXr1GwZZZxKG8ZRaUg,UgzejN2Rg4M03rI7myF4AaABAg,@harsharya3922,UCvEOfsftf4VqB8FB7NCfK8A,answers to question no 32 35 and 48 are far di...,1,2023-10-11T20:40:16Z,2023-10-11T20:40:16Z,20
28079,l7rdyynxlqU,UCxykVmXr1GwZZZxKG8ZRaUg,Ugx23ZGiE2oa1m1XC394AaABAg,@vikrantdubey7818,UCOPHfQ5ruOMmOPXAVpFZpjg,Aur your energy is..... unbelievable to believ...,1,2023-10-13T16:52:54Z,2023-10-13T16:52:54Z,14
28082,l7rdyynxlqU,UCxykVmXr1GwZZZxKG8ZRaUg,Ugz4vpkA-nTi7YTMC0B4AaABAg,@siddhantkedare4294,UC5Cg5Csd3OJDiox0ge6lIIg,Where Can I find these PDF in adda 247 acc,0,2023-10-13T02:07:39Z,2023-10-13T02:07:39Z,10
28083,l7rdyynxlqU,UCxykVmXr1GwZZZxKG8ZRaUg,Ugxe8TwIHQhs0QUB34J4AaABAg,@exploringwithmonika7467,UCVgnANxn3th0nezFf2fv1eQ,Same energy maintain till last question ❤very ...,4,2023-10-12T16:56:51Z,2023-10-12T16:56:51Z,20
28087,2lEbFBYybDo,UCxykVmXr1GwZZZxKG8ZRaUg,UgziYRSXkEdp2dmFmTJ4AaABAg,@anmoljadhav123,UCvGeqmoDRDvRl9EawCeatFA,"Thanks for the session mam , my exam went well...",0,2023-10-15T11:24:35Z,2023-10-15T11:24:35Z,18

In [107]:
df = df.drop_duplicates(subset = ["text_display"])
df

,video_id,channel_id,comment_id,author_display_name,author_channel_id,text_display,like_count,published_at,updated_at,quality_score
7,0voLlAL61uU,UCxykVmXr1GwZZZxKG8ZRaUg,UgxlUCWa6hZjGYlYToF4AaABAg,@akashukey1776,UC3qF3oGXTLXVjwSSih20-sA,sir i work in raigad but i want nagpur centre ...,0,2026-08-20T15:46:13Z,2026-08-20T15:46:13Z,16
8,0voLlAL61uU,UCxykVmXr1GwZZZxKG8ZRaUg,UgxmGGHMdRlPS0KKBGh4AaABAg,@Gamingbiason1992,UCU8qHDVkH5cReCoLMMEZCVA,Sir agar transfer ho Gaya ek state Se dusre st...,0,2026-05-05T03:11:32Z,2026-05-05T03:11:32Z,17
9,0voLlAL61uU,UCxykVmXr1GwZZZxKG8ZRaUg,UgxnMEb6wDYsA4ZFw8J4AaABAg,@twinkleverma4392,UCbper4TF3tilIR-qdy0pa7w,Sir if my place of work is mumbai can I select...,0,2025-08-21T17:40:44Z,2025-08-21T17:40:44Z,17
24,urO82djZqhE,UCxykVmXr1GwZZZxKG8ZRaUg,UgyFzrpBgjkJl2ol-vJ4AaABAg,@babulgupta4833,UC_LR4Ja6j9M-4FMaF4OM9mw,Mere pass id card nhi h ... bhar paunga ki nhi...,0,2025-08-27T19:29:57Z,2025-08-27T19:29:57Z,12
33,masJDyVfIzo,UCxykVmXr1GwZZZxKG8ZRaUg,Ugzi2B5hQirDpctlaIN4AaABAg,@kavitavashisth787,UCHN_pEggqtarwvPqQ9qTN6w,Mam pehle membership fees 1700 something lgii ...,0,2025-08-25T17:23:11Z,2025-08-25T17:23:11Z,22
...,...,...,...,...,...,...,...,...,...,...
28069,W2y9KGA0V-s,UCxykVmXr1GwZZZxKG8ZRaUg,UgzejN2Rg4M03rI7myF4AaABAg,@harsharya3922,UCvEOfsftf4VqB8FB7NCfK8A,answers to question no 32 35 and 48 are far di...,1,2023-10-11T20:40:16Z,2023-10-11T20:40:16Z,20
28079,l7rdyynxlqU,UCxykVmXr1GwZZZxKG8ZRaUg,Ugx23ZGiE2oa1m1XC394AaABAg,@vikrantdubey7818,UCOPHfQ5ruOMmOPXAVpFZpjg,Aur your energy is..... unbelievable to believ...,1,2023-10-13T16:52:54Z,2023-10-13T16:52:54Z,14
28082,l7rdyynxlqU,UCxykVmXr1GwZZZxKG8ZRaUg,Ugz4vpkA-nTi7YTMC0B4AaABAg,@siddhantkedare4294,UC5Cg5Csd3OJDiox0ge6lIIg,Where Can I find these PDF in adda 247 acc,0,2023-10-13T02:07:39Z,2023-10-13T02:07:39Z,10
28083,l7rdyynxlqU,UCxykVmXr1GwZZZxKG8ZRaUg,Ugxe8TwIHQhs0QUB34J4AaABAg,@exploringwithmonika7467,UCVgnANxn3th0nezFf2fv1eQ,Same energy maintain till last question ❤very ...,4,2023-10-12T16:56:51Z,2023-10-12T16:56:51Z,20
28087,2lEbFBYybDo,UCxykVmXr1GwZZZxKG8ZRaUg,UgziYRSXkEdp2dmFmTJ4AaABAg,@anmoljadhav123,UCvGeqmoDRDvRl9EawCeatFA,"Thanks for the session mam , my exam went well...",0,2023-10-15T11:24:35Z,2023-10-15T11:24:35Z,18

In [108]:
df["text_display"] = df["text_display"].replace(r"https?://\S+|www\.\S+", "", regex = True).iloc[:]
df["text_display"] = df["text_display"].replace(r"<[^<>]*>", "", regex = True)
df["text_display"] = df["text_display"].replace(r"['’][sS]\b","",regex = True)
df["text_display"] = df["text_display"].replace(r"\b\d{1,2}:\d{2}(:\d{2})?\b", "", regex = True)
df["text_display"] = df["text_display"].replace(r"\s+"," ", regex = True).str.strip()
df["text_display"] = df["text_display"].replace(r"(.)\1{2,}", r"\1\1", regex = True)
df["text_display"] = df["text_display"].apply(html.unescape)

/tmp/ipykernel_659/1425114547.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["text_display"] = df["text_display"].replace(r"https?://\S+|www\.\S+", "", regex = True).iloc[:]
/tmp/ipykernel_659/1425114547.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["text_display"] = df["text_display"].replace(r"<[^<>]*>", "", regex = True)
/tmp/ipykernel_659/1425114547.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["text_display"] = df["text_display"].replace(r"['’][sS]\b","",regex = True)
/tmp/ipykernel_659/1425114547.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["text_display"] = df["text_display"].replace(r"\b\d{1,2}:\d{2}(:\d{2})?\b", "", regex = True)
/tmp/ipykernel_659/1425114547.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["text_display"] = df["text_display"].replace(r"\s+"," ", regex = True).str.strip()
/tmp/ipykernel_659/1425114547.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["text_display"] = df["text_display"].replace(r"(.)\1{2,}", r"\1\1", regex = True)
/tmp/ipykernel_659/1425114547.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["text_display"] = df["text_display"].apply(html.unescape)

In [109]:
latin_count = df["text_display"].str.count(r'[a-zA-Z0-9\s.,?!’\'"]')
total_count = df["text_display"].str.len()
# Set 0 total count to 1 to avoid Division by Zero errors
ratio = latin_count / total_count.replace(0, 1)
df = df[ratio > 0.9]

In [110]:
df["text_display"]

7        sir i work in raigad but i want nagpur centre ...
8        Sir agar transfer ho Gaya ek state Se dusre st...
9        Sir if my place of work is mumbai can I select...
24       Mere pass id card nhi h .. bhar paunga ki nhi ...
33       Mam pehle membership fees 1700 something lgii ...
                               ...
28069    answers to question no 32 35 and 48 are far di...
28079    Aur your energy is.. unbelievable to believe.....
28082           Where Can I find these PDF in adda 247 acc
28083    Same energy maintain till last question ❤very ...
28087    Thanks for the session mam , my exam went well...
Name: text_display, Length: 5227, dtype: object

In [111]:
df = df.groupby('video_id')['text_display'].apply(lambda x: ' '.join(x)).reset_index()

In [112]:
df

         video_id                                       text_display
0     -38w7nqR1PE  Nice class mam lekin aap padhne ni dete bar ba...
1     -CwkZPG0wYw  Mam.. It means a lot.. This motivation 💪 is wh...
2     -GGkXfuE9uY  Class puri nahi h mam, video bhi uload nahi hui h
3     -HFc3QZc3ok  how can we cancel 30 by 30 while it is in plus...
4     -L_VOrM9jPg  Sir mera last yhi reh gya tha bas ye bhi ho gy...
...           ...                                                ...
1448  zmCUrSwIfAw  Mam aap bahut hi zyada beautiful ❤ho mai to si...
1449  zmnax3IUxoE  Ma'am is it possible to crack this exam with t...
1450  zpq7uM6hT8I     Sir ap uco Bank scal 1 ka preparation krwate h
1451  zupon4LkFNc  Thanks a lot ma'am for this wonderful session....
1452  zwN979XH89E  Yes audio, video are ok but at the end of the ...

[1453 rows x 2 columns]

In [113]:
len(df)

1453

In [114]:
vectorizer = CountVectorizer()
vec = vectorizer.fit_transform(df)
vec

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (2, 2)>

In [115]:
print(vec)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2 stored elements and shape (2, 2)>
  Coords	Values
  (0, 1)	1
  (1, 0)	1

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Define a baseline list of common Hinglish filler words that don't add educational value
hinglish_stop_words = [
    'hai', 'he', 'ho', 'ka', 'ki', 'ke', 'ko', 'se', 'bhi', 'na', 'ne',
    'kr', 'kar', 'karo', 'kya', 'tha', 'thi', 'the', 'par', 'per', 'toh',
    'toh', 'ya', 'aur', 'and', 'hi', 'ye', 'wo', 'hua', 'gaya', 'bhai'
]

# Combine with standard English stop words if you are using Scikit-Learn
from sklearn.feature_extraction import text
combined_stop_words = list(text.ENGLISH_STOP_WORDS.union(hinglish_stop_words))

# Now use this custom list in your vectorizer tool
tfidf = TfidfVectorizer(max_features=10000, stop_words=combined_stop_words)